INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 1, 'Lequel de ces objets à la forme d’un tore : une chaise, un sapin de Noël ou une bouée ?', 'Cette question est évidente pour n''importe qui qui à déjà entendu parler de tore', 'Cette question est évidente pour n''importe qui qui à déjà entendu parler de tore', 'une bouée', 'Un tore est une surface géometrique qui ressemble à une bouée, selon les paramètres que l''on choisit, il peut ressembler plutot a un anneau ou plutot à un donut.', '', 'https://fr.wikipedia.org/wiki/Tore', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 2, 'Combien possède de trous un tore simple ?', '', '', '1', '', '', 'https://fr.wikipedia.org/wiki/Tore', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 2, 'Citer un jeu qui utilise les propriétés du tore dans les déplacements des personnages ?', '', '', 'PacMan', '', '', 'https://analysis-situs.math.cnrs.fr/Les-premieres-surfaces-la-sphere-le-cylindre-le-tore.html', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 3, 'Lequel de ces objets est homéomorphe à un tore : un bol, une tasse, un verre à pied ?', '', '', 'Une tasse', '', '', 'https://fr.wikipedia.org/wiki/Hom%C3%A9omorphisme', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 4, 'Le théorème des 4 couleurs énonce qu’il n’y a besoin que de 4 couleurs pour colorier les différentes parties d’une carte sur un plan, celui-ci est faux sur un tore. Combien faut-il au minimum de couleur dans ce cas ?', '', '', '7', '', '', 'https://fr.wikipedia.org/wiki/Tore#Colorier_un_tore', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 5, 'Quelle est la caractéristique d’Euler du tore ?', '', '', '0', '', '', 'https://fr.wikipedia.org/wiki/Tore#Caract%C3%A9ristique_d''Euler_d''un_tore', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 6, 'Laquelle de ces définitions du tore n’est pas correcte : $\mathbb{R}/\mathbb{Z}\times\mathbb{R}/\mathbb{Z}$, $\mathbb{S}_1 \times \mathbb{S}_1$ ou $\sqrt{x^2+y^2+z^2}=R^2-r^2$', '', '', '$\sqrt{x^2+y^2+z^2}=R^2-r^2$', '', '', 'https://fr.wikipedia.org/wiki/Tore#%C3%89quations_du_tore', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 7, 'De quelle manière faut-il sectionner un tore pour obtenir les cercles de Villarceau ?', '', '', 'Selon un plan diagonal bitangent qui passe par le centre du tore.', '', 'une description “avec les mains” peut être acceptée', 'https://fr.wikipedia.org/wiki/Tore#Cercles_de_Villarceau', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 8, 'En électricité, pour le circuit magnétique de quelle machine électrique utilise-t-on idéalement le tore ?', '', '', 'Le transformateur', '', 'La bobine de manière générale est acceptée.', 'https://fr.wikipedia.org/wiki/Tore#Applications', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 9, 'Qu’est-ce que le tore de Stanford ?', '', '', 'Il s’agit d’un design imaginé pour la fabrication de mégatructures spatiales et ayant pour objectif de recréer artificiellement la gravité terrestre par effet centrifuge.', '', '', 'https://fr.wikipedia.org/wiki/Tore_de_Stanford', '');
INSERT INTO questions (subject_id, level, statement, hint, question_comment, answer, explanation, answer_comment, answer_source, origin_source)
        VALUES (1, 10, 'Parmi les différents modèles mathématiques cherchant une description géométrique de l’univers, il existe celle d’un tore tridimensionnel. Cette description n’est pourtant pas la plus répandue. Pour quelle raison ?', '', '', 'Car le tore tridimensionnel n’est pas simplement connexe.', '', '', 'https://fr.wikipedia.org/wiki/Univers_en_tore_bidimensionnel', '');
